spring.application.name=NotesApp

spring.datasource.username=postgres
spring.datasource.password=Hsp@11347890
spring.datasource.url=jdbc:postgresql://localhost:5432/NotesApp

logging.level.root=WARN
logging.level.com.harsh.notesapp=DEBUG
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.file.name=logs/application.log

spring.jpa.hibernate.ddl-auto=update
