spring.application.name=NotesApp

spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.url=jdbc:postgresql://localhost:5432/NotesApp

spring.jpa.hibernate.ddl-auto=update
